name: Build and Upload FFmpeg

on:
workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-ffmpeg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf automake build-essential cmake git libtool libva-dev pkg-config \
            python3 python3-dev x264 libx264-dev
          sudo apt-get install -y \
            meson ninja-build

      - name: Build MPP
        run: |
          mkdir -p ~/dev && cd ~/dev
          git clone -b jellyfin-mpp --depth=1 https://github.com/nyanmisaka/mpp.git rkmpp
          cd rkmpp
          mkdir rkmpp_build
          cd rkmpp_build
          cmake \
              -DCMAKE_INSTALL_PREFIX=/usr \
              -DCMAKE_BUILD_TYPE=Release \
              -DBUILD_SHARED_LIBS=ON \
              -DBUILD_TEST=OFF \
              ..
          make -j $(nproc)
          sudo make install

      - name: Build RGA
        run: |
          mkdir -p ~/dev && cd ~/dev
          git clone -b jellyfin-rga --depth=1 https://github.com/nyanmisaka/rk-mirrors.git rkrga
          cd rkrga
          meson setup rkrga_build \
              --prefix=/usr \
              --libdir=lib \
              --buildtype=release \
              --default-library=shared \
              -Dcpp_args=-fpermissive \
              -Dlibdrm=false \
              -Dlibrga_demo=false
          meson configure rkrga_build
          ninja -C rkrga_build install

      - name: Build FFmpeg
        run: |
          mkdir -p ~/dev && cd ~/dev
          git clone --depth=1 https://github.com/nyanmisaka/ffmpeg-rockchip.git ffmpeg
          cd ffmpeg
          ./configure --prefix=/usr --enable-gpl --enable-version3 --enable-libdrm --enable-rkmpp --enable-rkrga
          make -j $(nproc)
          ./ffmpeg -decoders | grep rkmpp
          ./ffmpeg -encoders | grep rkmpp
          ./ffmpeg -filters | grep rkrga

      - name: Upload FFmpeg Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-$(arch)
          path: ~/dev/ffmpeg/ffmpeg
